import logging
from cryptography.fernet import Fernet, InvalidToken

logger = logging.getLogger(__name__)

def encrypt_password(plain_password: str, key: str) -> str:
    """
    Encrypts a plain text password using the provided symmetric key.
    
    Args:
        plain_password: The plaintext password (e.g., SMTP app password).
        key: A base64-encoded 32-byte key generated by cryptography.fernet.Fernet.generate_key()
             retrieved from the application's config ENCRYPTION_KEY.
             
    Returns:
        The encrypted password string, safe for DB storage.
    """
    if not plain_password:
        return ""
    if not key:
        logger.error("ENCRYPTION_KEY is missing but encryption was attempted.")
        raise ValueError("Encryption key cannot be empty.")
        
    try:
        f = Fernet(key.encode('utf-8'))
        token = f.encrypt(plain_password.encode('utf-8'))
        return token.decode('utf-8')
    except Exception as e:
        logger.error(f"Failed to encrypt password: {str(e)}")
        raise

def decrypt_password(encrypted_password: str, key: str) -> str:
    """
    Decrypts an encrypted password using the provided symmetric key.
    
    Args:
        encrypted_password: The encrypted string retrieved from the database.
        key: The base64-encoded symmetric key from config ENCRYPTION_KEY.
        
    Returns:
        The decrypted plaintext password.
    """
    if not encrypted_password:
        return ""
    if not key:
        logger.error("ENCRYPTION_KEY is missing but decryption was attempted.")
        raise ValueError("Encryption key cannot be empty.")
        
    try:
        f = Fernet(key.encode('utf-8'))
        decrypted = f.decrypt(encrypted_password.encode('utf-8'))
        return decrypted.decode('utf-8')
    except InvalidToken:
        logger.error("Failed to decrypt password: Invalid token or incorrect key.")
        raise ValueError("Invalid encryption key or corrupted data.")
    except Exception as e:
        logger.error(f"Failed to decrypt password: {str(e)}")
        raise
